sudo: false
language: java
jdk: oraclejdk8
install: true
script: ./gradlew build
before_deploy: ./gradlew generatePomFileForMyPublicationPublication generateBintrayFile
deploy:
  provider: bintray
  file: ""
  user: "frc-1294"
  key: ""
  dry-run: true
  on:
    all_branches: true
